steps:
  - id: 'clone-community'
    name: 'gcr.io/cloud-builders/git'
    args: [ 'clone', 'https://github.com/GoogleCloudPlatform/cloud-builders-community']

  - id: 'submit-firebase-container-image'
    name: 'gcr.io/cloud-builders/gcloud'
    args: [ 'builds', 'submit', '--config', 'cloudbuild.yaml', '.']
    dir: './cloud-builders-community/firebase'

  - name: 'gcr.io/cloud-builders/npm'
    dir: 'functions'
    args: ['install']

  - name: 'gcr.io/$PROJECT_ID/firebase'
    dir: 'functions'
    args: [ 'deploy', '--only', 'functions', '--project', '${PROJECT_ID}']