steps:
  - id: 'clone-community'
    name: 'gcr.io/cloud-builders/git'
    args: [ 'clone', 'https://github.com/GoogleCloudPlatform/cloud-builders-community']

  - id: 'submit-firebase-container-image'
    name: 'gcr.io/cloud-builders/gcloud'
    args: [ 'builds', 'submit', '--config', 'cloudbuild.yaml', '.']
    dir: './cloud-builders-community/firebase'

  - name: 'node:8'
    dir: './multilanguage-functions'
    entrypoint: 'npm'
    args: ['install']

  - name: 'gcr.io/$PROJECT_ID/firebase'
    dir: './multilanguage-functions'
    args: [ 'functions:config:set', 'suggestions.spreadsheet_id=${_SUGGESTIONS_SPREADSHEET}',
            'feedback.spreadsheet_id=${_FEEDBACK_SPREADSHEET}', '--project', '${PROJECT_ID}']

  - name: 'gcr.io/$PROJECT_ID/firebase'
    dir: './multilanguage-functions'
    args: [ 'deploy', '--only', 'functions', '--project', '${PROJECT_ID}']